import { build } from "esbuild";
import { chromium } from "playwright";
import { createServer } from "node:http";
import { mkdtemp, readFile, rm, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { existsSync } from "node:fs";
import assert from "node:assert/strict";
const root = resolve(".");
const temporary = await mkdtemp(join(tmpdir(), "tietiezhi-ui-"));
const chromePath = process.env.CHROME_PATH || "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
let browser, server;
try {
  await build({ entryPoints: [join(root, "tests/browser/main.jsx")], outfile: join(temporary, "app.js"), bundle: true,
    format: "iife", platform: "browser", jsx: "automatic", define: { "process.env.NODE_ENV": '"test"' }, alias: { "react-native": "react-native-web" },
    plugins: [{ name: "preview-sdk", setup(builder) { builder.onResolve({ filter: /^@getpaseo\/plugin\/client(?:\/(react-native|ui))?$/ }, () => ({ path: join(root, "tests/browser/sdk.jsx") })); } }],
  });
  server = createServer(async (request, response) => {
    if (request.url === "/app.js") { response.setHeader("Content-Type", "application/javascript; charset=utf-8"); response.end(await readFile(join(temporary, "app.js"))); return; }
    response.setHeader("Content-Type", "text/html; charset=utf-8"); response.end('<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0}</style></head><body><div id="root"></div><script src="/app.js"></script></body></html>');
  });
  await new Promise((done) => server.listen(0, "127.0.0.1", done));
  browser = await chromium.launch({ headless: true, ...(existsSync(chromePath) ? { executablePath: chromePath } : {}) });
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  const errors = []; page.on("pageerror", (error) => console.error("[PAGEERROR]", error));
  page.on("console", (msg) => console.log("[BROWSER]", msg.text()));
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.getByTestId("agent-row").first().waitFor();
  assert.equal(await page.getByTestId("agent-row").count(), 2);
  assert.deepEqual(await page.evaluate(() => globalThis.__preview.sidebarItems()), { header: [], footer: ["footer-demo"] });
  const footer = page.getByTestId("quota-footer-trigger");
  const panel = page.getByRole("dialog", { name: "模型额度", exact: true });
  assert.equal(await page.evaluate(() => globalThis.__preview.pillRegistrations()), 0);
  assert.equal(await page.getByTestId("composer-quota-pill").count(), 0);
  async function quotaLabel(label, value) {
    const vendor = label.split(" · ")[0];
    const expected = value === null ? `${vendor === "OpenCode Go" ? "Go" : vendor === "Antigravity" ? "AG" : vendor} · 未获取` : `${vendor} ${value}% · ${label.includes("缓存") ? "缓存 · " : ""}2 小时后重置`;
    await page.getByRole("button", { name: value === null ? expected : new RegExp("^" + expected.replace("2 小时", "[23] 小时") + "$"), exact: true }).waitFor();
    assert.equal(await page.getByTestId("quota-footer-bar").count(), 0);
    assert.equal(await page.getByTestId("quota-footer-card").getByText("测试账号 A", { exact: true }).count(), 0);
  }
  await quotaLabel("Codex · 剩余 72%", 72);
  await page.getByTestId("quota-footer-card").getByRole("img", { name: "OpenAI" }).waitFor();
  assert.match(await page.getByTestId("quota-footer-countdown").innerText(), /^[1-9]\d*小时(\d+分钟)?后$/);
  assert.equal(await page.getByTestId("quota-footer-level").count(), 0);
  assert.equal(await page.getByTestId("quota-footer-expiry").count(), 0);
  const iconBox = await page.getByTestId("quota-footer-card").getByRole("img", { name: "OpenAI" }).boundingBox();
  const countdownBox = await page.getByTestId("quota-footer-countdown").boundingBox();
  const meterBox = await page.getByTestId("quota-footer-refresh").boundingBox();
  assert.ok(Math.abs((iconBox.y + iconBox.height / 2) - (countdownBox.y + countdownBox.height / 2)) < 2, "图标和文字应垂直居中");
  const circle = page.getByTestId("quota-footer-refresh").getByLabel("剩余额度 72%", { exact: true });
  const circleBox = await circle.boundingBox();
  assert.equal(circleBox.width, 14);
  assert.equal(circleBox.height, 14);
  assert.equal(await page.getByTestId("quota-footer-arc").count(), 0);
  const percentBox = await page.getByTestId("quota-footer-refresh").getByText("72%", { exact: true }).boundingBox();
  assert.ok(circleBox.x + circleBox.width <= percentBox.x, "圆环应在剩余额度左侧");
  assert.ok(Math.abs((percentBox.y + percentBox.height / 2) - (circleBox.y + circleBox.height / 2)) < 2, "百分比和圆环在同一行居中");
  assert.ok(meterBox.x - (countdownBox.x + countdownBox.width) >= 10, "时间与额度在左右两端");
  assert.ok(countdownBox.x + countdownBox.width <= meterBox.x, "文字不能重叠额度仪表");
  await page.getByTestId("quota-footer-refresh").getByText("72%", { exact: true }).waitFor();
  await page.getByTestId("quota-footer-refresh").getByLabel("剩余额度 72%", { exact: true }).waitFor();
  const add = await page.getByTestId("sidebar-add-project").boundingBox(), card = await page.getByTestId("quota-footer-card").boundingBox(), icons = await page.getByTestId("sidebar-system-icons").boundingBox();
  assert.ok(card.height <= 44, "额度入口必须只有一行");
  assert.ok(add.y + add.height <= card.y + 1); assert.ok(card.y + card.height <= icons.y + 1); assert.ok(icons.y + icons.height <= 901);
  await page.getByTestId("sidebar-project-scroll").evaluate((element) => { element.scrollTop = element.scrollHeight; });
  assert.deepEqual(await page.getByTestId("quota-footer-card").boundingBox(), card);
  await mkdir(join(root, ".artifacts/ui"), { recursive: true });
  await page.screenshot({ path: join(root, ".artifacts/ui/pi-quota-footer-desktop-dark.png") });
  await page.getByTestId("quota-footer-card").screenshot({ path: join(root, ".artifacts/ui/quota-footer-one-line-dark.png") });
  // Reproduce the user's narrow sidebar with a multi-day countdown.
  await page.getByTestId("demo-sidebar-preview").evaluate((element) => { element.style.width = "190px"; });
  await page.evaluate(() => globalThis.__preview.quotaResetOffset((5 * 86400 + 19 * 3600 + 5 * 60 + 7) * 1000));
  await page.getByTestId("quota-footer-refresh").click();
  await page.waitForFunction(() => document.querySelector('[data-testid="quota-footer-countdown"]').textContent.includes("后"));
  await page.keyboard.press("Escape");
  assert.equal(await page.getByTestId("quota-footer-countdown").evaluate((element) => element.scrollWidth <= element.clientWidth + 1), true, "窄栏倒计时不能被省略号截断");
  const narrowTime = await page.getByTestId("quota-footer-countdown").boundingBox();
  const narrowMeter = await page.getByTestId("quota-footer-refresh").boundingBox();
  assert.ok(narrowTime.x + narrowTime.width <= narrowMeter.x, "倒计时不能被圆环遮挡");
  await page.getByTestId("quota-footer-refresh").getByText("72%", { exact: true }).waitFor();
  assert.equal(await page.getByTestId("quota-footer-refresh").evaluate((element) => element.scrollWidth <= element.clientWidth + 1), true, "剩余额度不截断");
  await page.getByTestId("quota-footer-card").screenshot({ path: join(root, ".artifacts/ui/quota-footer-narrow-dark.png") });
  await page.evaluate(() => globalThis.__preview.quotaResetOffset(3 * 3600000));
  await page.getByTestId("demo-sidebar-preview").evaluate((element) => { element.style.width = "240px"; });
  await page.getByTestId("quota-footer-card").click();
  await panel.waitFor();
  await page.keyboard.press("Escape");
  await panel.waitFor({ state: "hidden" });
  await page.getByTestId("quota-footer-refresh").click();
  await panel.waitFor();
  await panel.getByTestId("quota-account-card").first().waitFor();
  assert.equal(await panel.getByTestId("quota-account-card").count(), 2);
  await panel.getByTestId("quota-account-card").nth(1).getByText("35%", { exact: true }).waitFor();
  await page.screenshot({ path: join(root, ".artifacts/ui/pi-quota-panel-desktop-dark.png") });
  assert.equal(await panel.getByText("账号切换 · MacBook-Air", { exact: true }).count(), 0);
  assert.equal(await panel.getByText("点击账号切换此 Host", { exact: false }).count(), 0);
  assert.equal(await panel.getByText("更新：", { exact: false }).count(), 0);
  assert.equal(await panel.getByTestId("quota-details").count(), 0);
  assert.equal(await panel.getByTestId("quota-refresh").count(), 0);
  assert.equal(await panel.getByTestId("quota-family-go").count(), 0);
  assert.ok(await panel.getByTestId("quota-family-codex").getByText("Codex", { exact: true }).evaluate((el) => parseFloat(getComputedStyle(el).fontSize) >= 13));
  assert.equal(await panel.getByText(/^提示/).count(), 0);
  assert.equal(await panel.getByText(/有效期|授权：/).count(), 0);
  const panelBody = await panel.getByTestId("quota-panel").boundingBox();
  const accountBody = await panel.getByTestId("quota-account-card").first().boundingBox();
  assert.ok(accountBody.width >= panelBody.width - 2, "账号卡铺满内容宽度，不留大段两侧空白");
  await panel.getByTestId("quota-login").click();
  await panel.getByTestId("quota-login-panel").waitFor();
  assert.equal(await page.evaluate(() => globalThis.__preview.calls.filter((c) => c.kind === "tietiezhi.login.start").length), 0, "仅打开入口不启动授权");
  await panel.getByRole("button", { name: "开始登录", exact: true }).click();
  await panel.getByText("ABCD-EFGH", { exact: true }).waitFor();
  await panel.getByRole("button", { name: "复制链接", exact: true }).click();
  await panel.getByRole("button", { name: "取消", exact: true }).click();
  await panel.getByTestId("quota-login-panel").waitFor({ state: "hidden" });
  await page.waitForFunction(() => globalThis.__preview.calls.some((c) => c.kind === "tietiezhi.login.cancel"));
  assert.equal(await page.evaluate(() => globalThis.__preview.calls.find((c) => c.kind === "tietiezhi.login.start").serverId), "local");
  assert.equal(await page.evaluate(() => globalThis.__preview.calls.filter((c) => c.kind === "switch").length), 0);
  await panel.getByRole("button", { name: "切换至 测试账号 B", exact: true }).click();
  await panel.getByTestId("account-confirmation").waitFor();
  assert.equal(await page.evaluate(() => globalThis.__preview.calls.filter((c) => c.kind === "switch").length), 0);
  await panel.getByRole("button", { name: "取消", exact: true }).click();
  await panel.getByRole("button", { name: "切换至 测试账号 B", exact: true }).click();
  await panel.getByTestId("confirm-account-switch").click();
  await panel.getByTestId("account-confirmation").waitFor({ state: "hidden" });
  await quotaLabel("Codex · 剩余 35%", 35);
  const switched = await page.evaluate(() => globalThis.__preview.calls.filter((c) => c.kind === "switch"));
  assert.equal(switched.length, 1); assert.equal(switched[0].serverId, "local"); assert.equal(switched[0].input.confirmed, true);
  await panel.getByRole("button", { name: "切换至 测试账号 A", exact: true }).click();
  await panel.getByTestId("confirm-account-switch").click();
  await quotaLabel("Codex · 剩余 72%", 72);
  // Changing channels cancels the old account confirmation; a late refresh must not populate another channel.
  await panel.getByRole("button", { name: "切换至 测试账号 B", exact: true }).click();
  await panel.getByTestId("quota-family-xai").click();
  await panel.getByTestId("account-confirmation").waitFor({ state: "hidden" });
  await panel.getByTestId("quota-family-codex").click();
  await panel.getByTestId("quota-account-card").first().waitFor();
  await page.evaluate(() => globalThis.__preview.delayNextQuota());
  await page.evaluate(() => { void globalThis.__preview.refreshPanelQuota(); });
  await panel.getByTestId("quota-family-antigravity").click();
  await page.evaluate(() => globalThis.__preview.releaseQuota());
  await panel.getByTestId("quota-family-antigravity").waitFor();
  assert.equal(await panel.getByTestId("quota-account-card").count(), 0);
  await page.keyboard.press("Escape"); await panel.waitFor({ state: "hidden" });

  // Dynamic model tracking: footer reflects currently active model in composer
  await page.evaluate(() => globalThis.__preview.selectModel("openai-codex-account-2/gpt-5.5"));
  await page.getByTestId("quota-footer-card").getByRole("img", { name: "OpenAI" }).waitFor();
  await page.evaluate(() => globalThis.__preview.selectModel("google/gemini-2.5-flash"));
  await page.getByTestId("quota-footer-card").getByRole("img", { name: "Antigravity" }).waitFor();
  await footer.click();
  await page.evaluate(() => globalThis.__preview.seedQuotaAccounts("antigravity", 24));
  await panel.getByTestId("quota-pool-gemini").first().waitFor();
  await panel.getByTestId("quota-pool-claude").first().waitFor();
  assert.equal(await panel.getByTestId("quota-account-card").count(), 24);
  await panel.getByTestId("quota-pool-gemini").first().getByText("本周", { exact: true }).waitFor();
  await panel.getByTestId("quota-pool-gemini").first().getByText("80%", { exact: true }).waitFor();
  await panel.getByTestId("quota-pool-claude").first().getByText("35%", { exact: true }).waitFor();
  const fixedTabs = await panel.getByTestId("quota-fixed-tabs").boundingBox();
  const fixedLogin = await panel.getByTestId("quota-login").boundingBox();
  const hostHeader = await panel.locator("header").boundingBox();
  await panel.getByTestId("quota-account-scroll").evaluate((el) => { el.scrollTop = el.scrollHeight; });
  await page.waitForTimeout(100);
  assert.deepEqual(await panel.getByTestId("quota-fixed-tabs").boundingBox(), fixedTabs, "账号多时 Tab 固定不滚动");
  assert.deepEqual(await panel.getByTestId("quota-login").boundingBox(), fixedLogin, "顶部登录固定不滚动");
  assert.deepEqual(await panel.locator("header").boundingBox(), hostHeader, "宿主 Title/关闭不随列表滚动");
  await panel.getByTestId("quota-account-scroll").evaluate((el) => { el.scrollTop = 0; });
  await page.screenshot({ path: join(root, ".artifacts/ui/antigravity-accounts-fixed-dark.png") });
  await page.evaluate(() => globalThis.__preview.seedQuotaAccounts("antigravity", 0));
  await page.evaluate(() => globalThis.__preview.seedQuotaAccounts("xai", 2));
  await panel.getByTestId("quota-family-xai").click();
  await panel.getByTestId("quota-account-card").first().waitFor();
  await page.screenshot({ path: join(root, ".artifacts/ui/grok-accounts-dark.png") });
  await page.evaluate(() => globalThis.__preview.seedQuotaAccounts("xai", 0));
  await page.evaluate(() => globalThis.__preview.selectModel("openai-codex-account-1/gpt-5.5"));
  await panel.getByTestId("quota-family-codex").click();
  await quotaLabel("Codex · 剩余 72%", 72);
  await page.keyboard.press("Escape");
  await page.evaluate(() => globalThis.__preview.quotaFailure(true));
  await page.getByTestId("quota-footer-refresh").click();
  await quotaLabel("Codex · 剩余 72%（缓存）", 72);
  await page.evaluate(() => { void globalThis.__preview.refreshPanelQuota(); });
  await panel.getByTestId("quota-account-card").first().getByText("查询失败", { exact: true }).waitFor();
  assert.equal(await panel.getByText("模拟网络失败", { exact: true }).count(), 0);
  assert.equal(await panel.getByTestId("quota-details").count(), 0);
  await page.keyboard.press("Escape");
  await page.evaluate(() => globalThis.__preview.quotaFailure(false));
  await page.getByTestId("quota-footer-refresh").click();
  await quotaLabel("Codex · 剩余 72%", 72);
  await panel.getByRole("button", { name: "切换至 测试账号 B", exact: true }).click();
  await page.evaluate(() => globalThis.__preview.selectHost("remote"));
  await panel.waitFor({ state: "hidden" });
  await quotaLabel("Codex · 剩余 76%", 76);
  await page.evaluate(() => globalThis.__preview.offline());
  await quotaLabel("Codex · 剩余 76%（缓存）", 76);
  assert.equal(await page.getByTestId("quota-footer-refresh").getAttribute("aria-disabled"), "true");
  await footer.click(); await panel.getByText("离线 · 缓存", { exact: true }).waitFor();
  assert.equal(await panel.getByTestId("quota-account-card").count(), 2);
  assert.equal(await panel.getByTestId("quota-login").isDisabled(), true);
  const switchButtons = panel.getByRole("button", { name: /^切换至 / });
  for (let i = 0; i < await switchButtons.count(); i++) assert.equal(await switchButtons.nth(i).isDisabled(), true);
  await page.keyboard.press("Escape");
  await page.evaluate(() => { globalThis.__preview.online(); globalThis.__preview.selectHost("local"); });
  await quotaLabel("Codex · 剩余 72%", 72);

  assert.equal(await page.getByText("每 5 秒刷新当前可见列表", { exact: false }).count(), 0);
  const remote = page.getByTestId("agent-row").filter({ hasText: "远程构建任务" });
  assert.equal(await remote.getByText("shared-id", { exact: true }).count(), 0);
  await remote.getByTestId("agent-details").click();
  await remote.getByText("shared-id", { exact: true }).waitFor();
  await remote.getByTestId("agent-details").click();
  await remote.getByRole("button", { name: "打开会话" }).click();
  assert.deepEqual(await page.evaluate(() => globalThis.__preview.calls.find((c) => c.kind === "navigate")), { kind: "navigate", serverId: "remote", agentId: "shared-id" });
  await remote.getByRole("button", { name: "发消息", exact: true }).click();
  await page.getByTestId("agent-message-input").fill("preview message"); await page.getByTestId("confirm-agent-message").click();
  await page.getByTestId("agent-message-confirmation").waitFor({ state: "hidden" });
  const sent = await page.evaluate(() => globalThis.__preview.calls.filter((c) => c.kind === "send"));
  assert.equal(sent.length, 1); assert.equal(sent[0].serverId, "remote"); assert.equal(sent[0].options.activeTurnBehavior, "steer");
  await page.evaluate(() => globalThis.__preview.offline());
  await page.getByText("公网服务器 · 离线 · 缓存", { exact: true }).waitFor();
  assert.equal(await remote.getByRole("button", { name: "发消息", exact: true }).isDisabled(), true);
  await page.getByRole("button", { name: "显示子 Agent", exact: true }).click(); assert.equal(await page.getByTestId("agent-row").count(), 3);
  await page.getByTestId("agent-search").fill("MacBook"); assert.equal(await page.getByTestId("agent-row").count(), 1); await page.getByTestId("agent-search").fill("");



  await page.setViewportSize({ width: 390, height: 844 }); await page.evaluate(() => { globalThis.__preview.light(); globalThis.scrollTo(0, 0); });
  await page.screenshot({ path: join(root, ".artifacts/ui/pi-quota-footer-mobile-light.png") });
  await page.getByTestId("quota-footer-card").screenshot({ path: join(root, ".artifacts/ui/quota-footer-one-line-light.png") });
  await footer.click(); await panel.waitFor(); await page.screenshot({ path: join(root, ".artifacts/ui/pi-quota-panel-mobile-light.png") });
  await page.getByTestId("dialog-backdrop").click({ position: { x: 5, y: 5 } }); await panel.waitFor({ state: "hidden" });
  await page.getByTestId("tab-hosts").click();
  assert.equal(await page.getByText("远端启动 Paseo", { exact: false }).count(), 0);
  await page.getByTestId("host-help").click(); await page.getByText("远端启动 Paseo", { exact: false }).waitFor();
  await page.getByTestId("host-help").click();
  await page.getByRole("button", { name: "查看官方连接文档", exact: true }).click();
  assert.equal(await page.evaluate(() => globalThis.__preview.calls.some((c) => c.kind === "external")), true);
  await page.screenshot({ path: join(root, ".artifacts/ui/hosts-compact-mobile-light.png") });
  await page.getByTestId("tab-accounts").click();
  await page.getByRole("button", { name: "切换至 测试账号 B", exact: true }).waitFor();
  assert.equal(await page.getByText("本页只管理此插件所在", { exact: false }).count(), 0);
  await page.screenshot({ path: join(root, ".artifacts/ui/accounts-compact-mobile-light.png") });
  await page.getByTestId("tab-agents").click();
  await page.screenshot({ path: join(root, ".artifacts/ui/agents-compact-mobile-light.png") });
  await footer.click(); await panel.waitFor(); await page.evaluate(() => globalThis.__preview.stopPlugin());
  await panel.waitFor({ state: "hidden" }); await page.getByTestId("quota-footer-card").waitFor({ state: "hidden" });
  assert.deepEqual(await page.evaluate(() => globalThis.__preview.sidebarItems()), { header: [], footer: [] });
  assert.deepEqual(errors, []);
  assert.equal(await page.evaluate(() => globalThis.__preview.pillRegistrations()), 0);
  console.log("UI regression passed: single-line sidebar footer, zero composer pills, compact cards, vendor icons, confirmed switch-back, Host/channel isolation, offline guards, dark desktop/light mobile, teardown.");
} finally { await browser?.close(); if (server) await new Promise((done) => server.close(done)); await rm(temporary, { recursive: true, force: true }); }
